2025-10-15 19:06:20,551 - ERROR - Необработанное исключение: CoachDoesNotExist: <Model: Coach> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`coach` FROM `coachs` AS `t1` WHERE (`t1`.`id` = %s) LIMIT %s OFFSET %s
Params: [1498, 1, 0]
2025-10-15 19:06:20,553 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 7297, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 4583, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v6\main.py", line 3737, in dclick_in_listwidget
    coaches = Coach.get(Coach.id == player_full[0])
  File "c:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 6840, in get
    return sq.get()
           ~~~~~~^^
  File "c:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 7300, in get
    raise self.model.DoesNotExist('%s instance matching query does '
                                  'not exist:\nSQL: %s\nParams: %s' %
                                  (clone.model, sql, params))
models.CoachDoesNotExist: <Model: Coach> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`coach` FROM `coachs` AS `t1` WHERE (`t1`.`id` = %s) LIMIT %s OFFSET %s
Params: [1498, 1, 0]
