2025-10-16 15:38:45,433 - ERROR - Необработанное исключение: Game_listDoesNotExist: <Model: Game_list> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`number_group`, `t1`.`rank_num_player`, `t1`.`player_group_id`, `t1`.`system_id`, `t1`.`title_id`, `t1`.`sex`, `t1`.`player_double_id` FROM `game_lists` AS `t1` WHERE ((`t1`.`title_id` = %s) AND (`t1`.`player_group_id` = %s)) LIMIT %s OFFSET %s
Params: [26, 2361, 1, 0]
2025-10-16 15:38:45,433 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "C:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 7297, in get
    return clone.execute(database)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 4583, in __getitem__
    return self.row_cache[item]
           ~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v6\main.py", line 6830, in delete_player
    game_lists = game_list.select().where(Game_list.player_group_id == player_id).get()
  File "C:\Users\Alex\Competitions_TT_v6\venv\Lib\site-packages\peewee.py", line 7300, in get
    raise self.model.DoesNotExist('%s instance matching query does '
                                  'not exist:\nSQL: %s\nParams: %s' %
                                  (clone.model, sql, params))
models.Game_listDoesNotExist: <Model: Game_list> instance matching query does not exist:
SQL: SELECT `t1`.`id`, `t1`.`number_group`, `t1`.`rank_num_player`, `t1`.`player_group_id`, `t1`.`system_id`, `t1`.`title_id`, `t1`.`sex`, `t1`.`player_double_id` FROM `game_lists` AS `t1` WHERE ((`t1`.`title_id` = %s) AND (`t1`.`player_group_id` = %s)) LIMIT %s OFFSET %s
Params: [26, 2361, 1, 0]
